export const districts = [
    'Achham', 'Arghakhanchi', 'Baglung', 'Baitadi', 'Bajhang', 'Bajura', 'Banke', 'Bara', 'Bardiya', 'Bhaktapur', 'Bhojpur', 'Chitwan', 'Dadeldhura', 'Dailekh', 'Dang', 'Darchula', 'Dhading', 'Dhankuta', 'Dhanusha', 'Dolakha', 'Dolpa', 'Doti', 'Gorkha', 'Gulmi', 'Humla', 'Ilam', 'Jajarkot', 'Jhapa', 'Jumla', 'Kailali', 'Kalikot', 'Kanchanpur', 'Kapilvastu', 'Kaski', 'Kathmandu', 'Kavrepalanchok', 'Khotang', 'Lalitpur', 'Lamjung', 'Mahottari', 'Makwanpur', 'Manang', 'Morang', 'Mugu', 'Mustang', 'Myagdi', 'Nawalpur', 'Nuwakot', 'Okhaldhunga', 'Palpa', 'Panchthar', 'Parasi', 'Parbat', 'Parsa', 'Pyuthan', 'Ramechhap', 'Rasuwa', 'Rautahat', 'Rolpa', 'Rukum East', 'Rukum West', 'Rupandehi', 'Salyan', 'Sankhuwasabha', 'Saptari', 'Sarlahi', 'Sindhuli', 'Sindhupalchok', 'Siraha', 'Solukhumbu', 'Sunsari', 'Surkhet', 'Syangja', 'Tanahun', 'Taplejung', 'Terhathum', 'Udayapur'
].sort();

export const municipalitiesByDistrict = {
    Achham: ['Bannigadhi Jayagadh', 'Chaurpati', 'Dhakari', 'Kamalbazar', 'Mellekh', 'Panchadewal Binayak', 'Ramaroshan', 'Sanphebagar', 'Turmakhad'],
    Arghakhanchi: ['Sandhikharka', 'Sitganga', 'Bhumikasthan', 'Chhatradev', 'Panini', 'Malarani'],
    Baglung: ['Baglung', 'Galkot', 'Jaimini', 'Dhorpatan', 'Bareng', 'Kathekhola', 'Tamankhola', 'Tarakhola', 'Nisikhola', 'Badigad'],
    Baitadi: ['Dasharathchand', 'Patan', 'Melauli', 'Purchaudi', 'Sunarya', 'Sigas', 'Shivanath', 'Pancheshwar', 'Dogadakedar', 'Dilasaini'],
    Bajhang: ['Jayaprithvi', 'Bungal', 'Talkot', 'Masta', 'Khaptadchhanna', 'Thalara', 'Bitthadchir', 'Surma', 'Chhabis Pathivere', 'Durgathali', 'Kedarsyu', 'Kanda'],
    Bajura: ['Badimalika', 'Triveni', 'Budhiganga', 'Budhinanda', 'Gaumul', 'Pandav Gupha', 'Swami Kartik', 'Chededaha', 'Himali'],
    Banke: ['Nepalgunj', 'Kohalpur', 'Narainapur', 'Rapti Sonari', 'Khajura', 'Janaki', 'Duduwa', 'Baijanath'],
    Bara: ['Kalaiya', 'Jeetpur Simara', 'Kolhabi', 'Nijgadh', 'Mahagadhimai', 'Simroungadh', 'Pacharauta', 'Pheta', 'Devtal', 'Suwarna', 'Karaiyamai', 'Prasouni', 'Bishrampur', 'Adarsh Kotwal', 'Baragadhi', 'Pariya'],
    Bardiya: ['Gulariya', 'Rajapur', 'Madhuwan', 'Thakurbaba', 'Bansgadhi', 'Barbardiya', 'Badhaiyatal', 'Geruwa'],
    Bhaktapur: ['Bhaktapur', 'Madhyapur Thimi', 'Suryabinayak', 'Changunarayan'],
    Bhojpur: ['Bhojpur', 'Shadananda', 'Tyamke Maiyum', 'Ramprasad Rai', 'Arun', 'Pauwadumma', 'Salpasilichho', 'Aamchok', 'Hatuwagadhi'],
    Chitwan: ['Bharatpur', 'Ratnanagar', 'Khairahani', 'Rapti', 'Kalika', 'Madi', 'Ichchhakamana'],
    Dadeldhura: ['Amargadhi', 'Parshuram', 'Aalital', 'Bhageshwar', 'Navadurga', 'Ajayameru', 'Ganyapadhura'],
    Dailekh: ['Narayan', 'Dullu', 'Chamunda Bindrasaini', 'Aathbis', 'Thantikandh', 'Bhairabi', 'Mahabu', 'Naumule', 'Dungeshwar', 'Gurans', 'Bhagawatimai'],
    Dang: ['Ghorahi', 'Tulsipur', 'Lamahi', 'Banglachuli', 'Dangisharan', 'Gadawa', 'Rajpur', 'Rapti', 'Shantinagar', 'Babai'],
    Darchula: ['Mahakali', 'Shailyasikhar', 'Malikarjun', 'Apihimal', 'Duhu', 'Naugad', 'Marma', 'Lekam', 'Vyans'],
    Dhading: ['Nilkantha', 'Khaniyabas', 'Gajuri', 'Galchhi', 'Gangajamuna', 'Jwalamukhi', 'Thakre', 'Netrawati Dabjong', 'Benighat Rorang', 'Ruby Valley', 'Siddhalek', 'Tripurasundari'],
    Dhankuta: ['Dhankuta', 'Pakhribas', 'Mahalaxmi', 'Sangurigadhi', 'Khalsha Mugatoghopa', 'Chhathar Jorpati', 'Sahidbhumi'],
    Dhanusha: ['Janakpur', 'Chireswarnath', 'Ganeshman Charnath', 'Dhanushadham', 'Nagarain', 'Bideh', 'Mithila', 'Sahidnagar', 'Sabaila', 'Kamala', 'Mithila Bihari', 'Hansapur', 'Janaknandani', 'Bateshwar', 'Mukhiyapatti Musharniya', 'Laxminiya', 'Aurahi', 'Dhanauji'],
    Dolakha: ['Bhimeshwar', 'Jiri', 'Kalinchok', 'Gauri Sankar', 'Baiteshwar', 'Sailung', 'Melung', 'Bigu', 'Tamakhoshi'],
    Dolpa: ['Thuli Bheri', 'Tripurasundari', 'Dolpo Buddha', 'She Phoksundo', 'Jagadulla', 'Mudkechula', 'Kaike', 'Chharka Tangsong'],
    Doti: ['Dipayal Silgadhi', 'Shikhar', 'Purbachouki', 'Badikedar', 'Jorayal', 'Sayamai', 'Adarsha', 'Kha Rasen', 'Bogatan'],
    Gorkha: ['Gorkha', 'Palungtar', 'Sulikhod', 'Siranchok', 'Ajirkot', 'Arughat', 'Gandaki', 'Chum Nubri', 'Dharche', 'Bhimsen Thapa', 'Sahid Lakhan'],
    Gulmi: ['Resunga', 'Musikot', 'Isma', 'Kaligandaki', 'Gulmi Durbar', 'Satyawati', 'Chandrakot', 'Ruru', 'Chhatrakot', 'Madane', 'Malika', 'Dhurkot'],
    Humla: ['Simkot', 'Namkha', 'Kharpunath', 'Sarkegad', 'Chhankheli', 'Adanchuli', 'Tajakot'],
    Ilam: ['Ilam', 'Deumai', 'Mai', 'Suryodaya', 'Fakphokthum', 'Chulachuli', 'Mai Jogmai', 'Mangsebung', 'Rong', 'Sandakpur'],
    Jajarkot: ['Bheri', 'Chhedagad', 'Nalgad', 'Barekot', 'Kushe', 'Junichande', 'Shivalaya'],
    Jhapa: ['Bhadrapur', 'Mechinagar', 'Arjundhara', 'Kankai', 'Damak', 'Birtamod', 'Shivasataksidham', 'Gauradaha', 'Gauriganj', 'Jhapa', 'Kachankawal', 'Kamal', 'Barhadashi', 'Haldibari', 'Buddhashanti'],
    Jumla: ['Chandannath', 'Kankasundari', 'Sinja', 'Hima', 'Tila', 'Guthichaur', 'Tatopani', 'Patarasi'],
    Kailali: ['Dhangadhi', 'Tikapur', 'Ghodaghodi', 'Bhajani', 'Lamki Chuha', 'Gauriganga', 'Godawari', 'Janaki', 'Bardgoriva', 'Mohanyal', 'Kailari', 'Joshipur', 'Chure'],
    Kalikot: ['Khandachakra', 'Rashi Kot', 'Tilagufa', 'Pachaljharana', 'Sanni Triveni', 'Narharinath', 'Shubha Kalika', 'Mahawai', 'Palata'],
    Kanchanpur: ['Bhimdatta', 'Bedkot', 'Krishnapur', 'Mahendranagar', 'Punarbas', 'Shuklaphanta', 'Belauri', 'Beldandi', 'Laljhadi'],
    Kapilvastu: ['Kapilvastu', 'Banganga', 'Buddhabhumi', 'Shivraj', 'Krishnanagar', 'Maharajgunj', 'Mayadevi', 'Yashodhara', 'Suddhodhan', 'Bijaynagar'],
    Kaski: ['Pokhara Metropolitan City', 'Annapurna', 'Machhapuchhre', 'Madi', 'Rupa'],
    Kathmandu: ['Kathmandu Metropolitan City', 'Kirtipur', 'Shankharapur', 'Kageshwari Manohara', 'Gokarneshwor', 'Budhanilkantha', 'Tarakeshwar', 'Tokha', 'Chandragiri', 'Nagarjun', 'Dakshinkali'],
    Kavrepalanchok: ['Dhulikhel', 'Banepa', 'Panauti', 'Panchkhal', 'Namobuddha', 'Mandandeupur', 'Khanikhola', 'Chauri Deurali', 'Temal', 'Bethanchok', 'Bhumlu', 'Mahabharat', 'Roshi'],
    Khotang: ['Rupakot Majhuwagadhi', 'Halesi Tuwachung', 'Khotehang', 'Diprung Chuichumma', 'Sakela', 'Kepilasgadhi', 'Bakshila', 'Rawabesi', 'Jantedhunga', 'Barahapokhari'],
    Lalitpur: ['Lalitpur Metropolitan City', 'Godawari', 'Mahalaxmi', 'Konjyosom', 'Bagmati', 'Mahankal'],
    Lamjung: ['Besishahar', 'Madhya Nepal', 'Rainas', 'Sundarbazar', 'Karaputar', 'Kwholasothar', 'Dordi', 'Marsyangdi'],
    Mahottari: ['Jaleshwar', 'Bardibas', 'Gaushala', 'Loharpatti', 'Ramgopalpur', 'Manra Siswa', 'Matihani', 'Bhangaha', 'Balwa', 'Aurahi', 'Sonama', 'Pipra', 'Samsi', 'Ekdara', 'Mahottari'],
    Makwanpur: ['Hetauda', 'Thaha', 'Indrasarowar', 'Kailash', 'Bakaiya', 'Bagmati', 'Manahari', 'Raksirang', 'Makawanpurgadhi', 'Bhimfedi'],
    Manang: ['Chame', 'Nason', 'Narpa Bhumi', 'Manang Ngisyang'],
    Morang: ['Biratnagar', 'Belbari', 'Letang', 'Pathari Sanischare', 'Rangeli', 'Ratuwamai', 'Sunawarshi', 'Urlabari', 'Sundar Haraicha', 'Budhiganga', 'Kanepokhari', 'Gramthan', 'Jahada', 'Kerabari', 'Miklajung'],
    Mugu: ['Chhayanath Rara', 'Mugum Karmarong', 'Soru', 'Khatyad'],
    Mustang: ['Gharapjhong', 'Thasang', 'Baragung Muktichhetra', 'Lomanthang', 'Lo-Ghekar Damodarkunda'],
    Myagdi: ['Beni', 'Annapurna', 'Dhaulagiri', 'Mangala', 'Malika', 'Raghuganga'],
    Nawalpur: ['Kawasoti', 'Gaidakot', 'Devchuli', 'Madhyabindu', 'Binayi Tribeni', 'Hupsekot', 'Bulingtar', 'Baidi Kali'],
    Nuwakot: ['Bidur', 'Belkotgadhi', 'Kakani', 'Panchakanya', 'Likhu', 'Dupcheswar', 'Shivapuri', 'Tadi', 'Suryagadhi', 'Kispang', 'Myagang', 'Tarkeshwar'],
    Okhaldhunga: ['Siddhicharan', 'Khiji Demba', 'Champadevi', 'Sunkoshi', 'Molung', 'Chisankhugadhi', 'Mane Bhanjyang', 'Likhu'],
    Palpa: ['Tansen', 'Rampur', 'Rainadevi Chhahara', 'Mathagadhi', 'Nisdi', 'Purbakhola', 'Bagnaskali', 'Mathagadhi', 'Tinau', 'Ribdikot'],
    Panchthar: ['Phidim', 'Phalelung', 'Phalgunanda', 'Hilihang', 'Kummayak', 'Miklajung', 'Tumbewa', 'Yangwarak'],
    Parasi: ['Ramgram', 'Sunwal', 'Bardaghat', 'Susta', 'Palhinandan', 'Pratappur', 'Sarawal'],
    Parbat: ['Kushma', 'Phalebas', 'Jaljala', 'Paiyun', 'Mahashila', 'Modi', 'Bihadi'],
    Parsa: ['Birgunj Metropolitan City', 'Pokhariya', 'Bahudarmai', 'Parsagadhi', 'Jagarnathpur', 'Dhobini', 'Chhipaharmai', 'Pakaha Mainpur', 'Bindabaasini', 'Irwa', 'Sakrauli', 'Patewa Sugauli', 'Thori'],
    Pyuthan: ['Pyuthan', 'Swargadwari', 'Gaumukhi', 'Mandavi', 'Sarumarani', 'Mallarani', 'Naubahini', 'Jhimruk', 'Airawati'],
    Ramechhap: ['Manthali', 'Ramechhap', 'Umakunda', 'Khandadevi', 'Gokulganga', 'Doramba', 'Likhu Tamakoshi', 'Sunapati'],
    Rasuwa: ['Uttargaya', 'Kalika', 'Gosaikunda', 'Naukunda', 'Parbatikunda'],
    Rautahat: ['Gaur', 'Garuda', 'Chandrapur', 'Ishanath', 'Gujara', 'Gadhimai', 'Fatuwa Vijayapur', 'Boudhimai', 'Brindaban', 'Dewahi Gonahi', 'Paroha', 'Rajpur', 'Rajdevi', 'Maulapur', 'Madhav Narayan', 'Yamunamai', 'Durga Bhagawati'],
    Rolpa: ['Rolpa', 'Triveni', 'Duikholi', 'Lungri', 'Sunchhari', 'Sukidaha', 'Gadhawa', 'Thawang', 'Parivesh', 'Runtigadhi'],
    'Rukum East': ['Bhume', 'Putha Uttarganga', 'Sisne'],
    'Rukum West': ['Musikot', 'Chaurjahari', 'Aathbiskot', 'Banfikot', 'Triveni', 'Sani Bheri'],
    Rupandehi: ['Butwal Metropolitan City', 'Siddharthanagar', 'Tilottama', 'Lumbini Sanskritik', 'Devdaha', 'Sainamaina', 'Gaidhawa', 'Kanchan', 'Kotahimai', 'Marchawari', 'Mayadevi', 'Omshatiya', 'Rohini', 'Sammarimai', 'Siyari', 'Suddhodhan'],
    Salyan: ['Shaarda', 'Bagchaur', 'Bangad Kupinde', 'Kalimati', 'Tribeni', 'Kapurkot', 'Chatreshwari', 'Darma', 'Kumakh Malika', 'Siddha Kumakh'],
    Sankhuwasabha: ['Khandbari', 'Chainpur', 'Madi', 'Dharmadevi', 'Panchkhapan', 'Shadanand', 'Bhotkhola', 'Chichila', 'Makalu', 'Silichong'],
    Saptari: ['Rajbiraj', 'Kanchanrup', 'Saptakoshi', 'Dakneshwari', 'Hanumannagar Kankalini', 'Shambhunath', 'Bode Barsain', 'Surunga', 'Khadak', 'Agnisair Krishna Savaran', 'Balan-Bihul', 'Bishnupur', 'Chhinnamasta', 'Mahadeva', 'Rupani', 'Tirhoot', 'Tilathi Koiladi'],
    Sarlahi: ['Malangwa', 'Harion', 'Ishwarpur', 'Lalbandi', 'Kabilasi', 'Godaita', 'Balara', 'Barahathwa', 'Bagmati', 'Gaureshwar', 'Hariwan', 'Haripur', 'Haripurwa', 'Kabilasi', 'Chakraghatta', 'Chandranagar', 'Dhankaul', 'Kaudena', 'Parsa', 'Ramnagar', 'Brahampuri'],
    Sindhuli: ['Kamalamai', 'Dudhouli', 'Golanjor', 'Ghyanglekh', 'Phikkal', 'Marin', 'Sunkoshi', 'Hariharpurgadhi', 'Tinpatan'],
    Sindhupalchok: ['Chautara Sangachokgadhi', 'Barhabise', 'Melamchi', 'Indrawati', 'Jugali', 'Panchpokhari Thangpal', 'Bhotekoshi', 'Lisankhu Pakhar', 'Sunkoshi', 'Helambu', 'Tripurasundari', 'Balephi'],
    Siraha: ['Siraha', 'Lahan', 'Mirchaiya', 'Golbazar', 'Dhangadhimai', 'Kalyanpur', 'Karjanha', 'Sukhipur', 'Bhagawanpur', 'Bishnupur', 'Bariyarpatti', 'Aurahi', 'Arnama', 'Navarajpur', 'Sakhuwanankarkatti', 'Naraha'],
    Solukhumbu: ['Solududhkunda', 'Dudhkoushika', 'Necha Salyan', 'Dudhkoshi', 'Maha Kulung', 'Sotang', 'Likhupike', 'Khumbu Pasang Lhamu'],
    Sunsari: ['Itahari', 'Dharan', 'Inaruwa', 'Duhabi', 'Ramdhuni', 'Baraha', 'Bhokraha', 'Dewanganj', 'Gadhi', 'Inaruwa', 'Jahada', 'Koshi', 'Sadananda'],
    Surkhet: ['Birendranagar', 'Bheri Ganga', 'Gurbha Kot', 'Panchapuri', 'Lekhbesi', 'Chaukune', 'Barahatal', 'Chingad', 'Simta'],
    Syangja: ['Putalibazar', 'Waling', 'Chapakot', 'Bhirkot', 'Galyang', 'Arjun Chaupari', 'Aandhikhola', 'Kaligandaki', 'Phedikhola', 'Harinas', 'Biruwa'],
    Tanahun: ['Byas', 'Shuklagandaki', 'Bhanu', 'Bhimad', 'Anbu Khaireni', 'Bandipur', 'Devghat', 'Myagde', 'Rhishing', 'Ghiring'],
    Taplejung: ['Phungling', 'Aathrai Tribeni', 'Sidingwa', 'Faktanglung', 'Mikwakhola', 'Meringden', 'Maiwakhola', 'Pathibhara Yangwarak', 'Sirijangha'],
    Terhathum: ['Myanglung', 'Lali Gurnans', 'Aathrai', 'Chhathar', 'Phedap', 'Menchayayem'],
    Udayapur: ['Triyuga', 'Katari', 'Chaudandigadhi', 'Belaka', 'Udayapurgadhi', 'Taapli', 'Rautamai', 'Sunkoshi']
};
